# Generated by Django 4.0.1 on 2022-02-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stapovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=40)),
                ('slika', models.ImageField(upload_to='')),
                ('kolicina', models.PositiveSmallIntegerField()),
                ('duzina', models.FloatField()),
                ('tezina_stapa', models.PositiveSmallIntegerField()),
                ('tezina_bacanja', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
