# Generated by Django 4.0.1 on 2022-02-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hrana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=40)),
                ('slika', models.ImageField(blank=True, upload_to='hrana')),
                ('tezina', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Hrana',
            },
        ),
        migrations.CreateModel(
            name='Mamci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=40)),
                ('slika', models.ImageField(blank=True, upload_to='mamci')),
            ],
            options={
                'verbose_name_plural': 'Mamci',
            },
        ),
        migrations.CreateModel(
            name='Masinice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=40)),
                ('slika', models.ImageField(blank=True, upload_to='masinice')),
                ('kolicina', models.PositiveSmallIntegerField()),
                ('tezina', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Masinice',
            },
        ),
        migrations.CreateModel(
            name='Ostalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=40)),
                ('slika', models.ImageField(blank=True, upload_to='ostalo')),
                ('duzina', models.PositiveSmallIntegerField(blank=True)),
                ('tezina', models.PositiveSmallIntegerField(blank=True)),
                ('ostalo', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ostalo',
            },
        ),
        migrations.CreateModel(
            name='Plovci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=40)),
                ('slika', models.ImageField(blank=True, upload_to='plovci')),
                ('duzina', models.PositiveSmallIntegerField(blank=True)),
                ('ampula', models.BooleanField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Plovci',
            },
        ),
        migrations.CreateModel(
            name='Strune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=40)),
                ('slika', models.ImageField(blank=True, upload_to='strune')),
            ],
            options={
                'verbose_name_plural': 'Strune',
            },
        ),
        migrations.CreateModel(
            name='Udice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=40)),
                ('slika', models.ImageField(blank=True, upload_to='hrana')),
                ('velicina', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Udice',
            },
        ),
        migrations.CreateModel(
            name='Varalice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=40)),
                ('slika', models.ImageField(blank=True, upload_to='varalice')),
                ('duzina', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Varalice',
            },
        ),
        migrations.AlterModelOptions(
            name='stapovi',
            options={'verbose_name_plural': 'Stapovi'},
        ),
        migrations.AlterField(
            model_name='stapovi',
            name='slika',
            field=models.ImageField(blank=True, upload_to='stapovi'),
        ),
    ]
