# Generated by Django 4.0.1 on 2022-02-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hrana_mamci_masinice_ostalo_plovci_strune_udice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ostalo',
            old_name='ostalo',
            new_name='opis',
        ),
        migrations.AddField(
            model_name='strune',
            name='duzina',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
