# Generated by Django 4.0.1 on 2022-02-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_ostalo_ostalo_opis_strune_duzina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ostalo',
            name='duzina',
        ),
        migrations.RemoveField(
            model_name='ostalo',
            name='tezina',
        ),
    ]
